apiVersion: v1
kind: Service
metadata:
  name: static-client
  namespace: ping
spec:
  selector:
    app: static-client
  ports:
    - port: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: static-client
  namespace: ping

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-client
  namespace: ping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-client
  template:
    metadata:
      name: static-client
      labels:
        app: static-client
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/connect-service-upstreams': 'google-https:1234'
    spec:
      containers:
        - name: static-client
          image: alpine:latest
          command: ["sh", "-c", "apk add --no-cache curl && sleep 3600"]
          args: ['while true; do sleep 30; done;']
      serviceAccountName: static-client
